# Generated by Django 5.2.8 on 2025-11-26 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availabel',
            new_name='is_available',
        ),
    ]
